// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user.proto

package user

import regexp "regexp"
import fmt "fmt"
import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _regex_User_Phone = regexp.MustCompile(`^(070|080|090)-\d{4}-\d{4}$`)
var _regex_User_Mail = regexp.MustCompile(`^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$`)

func (this *User) Validate() error {
	if !(this.Age > -1) {
		return github_com_mwitkow_go_proto_validators.FieldError("Age", fmt.Errorf(`value '%v' must be greater than '-1'`, this.Age))
	}
	if !(this.Age < 151) {
		return github_com_mwitkow_go_proto_validators.FieldError("Age", fmt.Errorf(`value '%v' must be less than '151'`, this.Age))
	}
	if !_regex_User_Phone.MatchString(this.Phone) {
		return github_com_mwitkow_go_proto_validators.FieldError("Phone", fmt.Errorf(`value '%v' must be a string conforming to regex "^(070|080|090)-\\d{4}-\\d{4}$"`, this.Phone))
	}
	if !_regex_User_Mail.MatchString(this.Mail) {
		return github_com_mwitkow_go_proto_validators.FieldError("Mail", fmt.Errorf(`value '%v' must be a string conforming to regex "^\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*$"`, this.Mail))
	}
	return nil
}
func (this *Name) Validate() error {
	return nil
}
func (this *Empty) Validate() error {
	return nil
}
func (this *Users) Validate() error {
	for _, item := range this.Users {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Users", err)
			}
		}
	}
	return nil
}
